#!/usr/bin/env python3
import util, sys
tx = 'e0238f53290502d8cc77547ec447ae2b8d473cd17607d05a301ea5a73f92bc93'
peers = {
    "66.42.93.69:50002:t"
}

results = util.send_request(peers, 'blockchain.transaction.get', [tx])

print(results)
